# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

flutter_application_path = '../closti_camera_plugin_test'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'CameraPluginTest' do
  install_all_flutter_pods(flutter_application_path)
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CameraPluginTest

end
